#:schema ../../../../schemas/source.json
layer = "source"
id = "recitpresentemon00mart"
type = "pamphlet"
title = "Récit présenté a Monseigneur de Calonne, ministre d'Etat, controleur-général des finances /"
language = "fr"
place = "France"
date = "1786"
note = """"Post-scriptum de l'editeur"--P. 67-76; dated: le 11 décembre 1786. Martin & Walter. Révolution française. NUC pre-1956. "Avis de l'editeur"--[2] p. at beginning; signed: Le marquis de L***. "Conclusion de l'editeur"--[2] p. at end; signed: Le marquis de L***. Bibliography: Martin & Walter.  Révolution française,  III, 23289. Scanner's note: No copyright page found. No table-of-contents pages found.  Title page and cover are combined. Damaged, stained, marked and/or loose pages. Uneven binding. Skewed text."""
url = "https://archive.org/details/recitpresentemon00mart"
subject = ["Finance, Public"]
extent = "[2], 76, [2] p., [1] leaf of plates : ill ; 20 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case FRC 22118"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t1kh5v51g"
internet_archive = "recitpresentemon00mart"
openlibrary_edition = "OL26240499M"
openlibrary_work = "OL17635022W"

[scan]
file = "recitpresentemon00mart.pdf"
count = 82
by = "Internet Archive"
url = "https://archive.org/details/recitpresentemon00mart"
ppi = 500
note = "Scanned on scribe4.indiana.archive.org with a Canon EOS 5D Mark II at the indiana centre."

[[resp]]
name = "Martin de Marivaux, Jacques Claude"
role = "author"

[[resp]]
name = "Calonne, Charles Alexandre de, 1734-1802"
role = "author"

[[resp]]
name = "s.n."
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_845873"

[[text]]
file = "recitpresentemon00mart.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p9.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p10.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p11.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p12.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p13.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p14.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p15.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p16.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p17.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p18.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p19.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p20.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p21.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p22.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p23.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p24.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p25.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p26.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p27.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p28.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p29.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p30.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p31.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p32.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p33.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p34.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p35.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p36.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p37.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p38.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p39.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p40.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p41.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p42.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p43.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p44.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p45.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p46.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p47.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p48.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p49.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p50.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p51.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p52.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p53.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p54.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p55.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p56.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p57.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p58.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p59.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p60.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p61.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p62.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p63.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p64.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p65.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p66.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p67.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p68.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p69.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p70.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p71.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p72.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p73.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p74.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p75.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p76.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p77.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p78.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p79.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "recitpresentemon00mart.p80.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"
