#:schema ../../../../../schemas/source.json
id    = "journal-de-paris-1789-04-12"
layer = "document"
of    = "journal-de-paris-1789-vol1"
type  = "issue"
no    = 102
date  = "1789-04-12"
pages = { from = 465, to = 468 }
