#:schema ../../../../schemas/source.json
layer = "source"
id = "plaidoyesecon00mari"
type = "pamphlet"
title = "Plaidoye' second"
language = "fr"
note = "Concerns the granting of a privilege for Muret's edition of Seneca. Dated at end: 15. mars 1586. Extracted from an unidentified publication. Scanner's note: No copyright found.  No table of contents found.  Damaged, stained pages and cover.  Title on cover page. <br />."
url = "https://archive.org/details/plaidoyesecon00mari"
subject = ["Printing"]

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case Wing folio Z144 .A1 v. 1 no. 14"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t0gv16s6t"
internet_archive = "plaidoyesecon00mari"

[scan]
file = "plaidoyesecon00mari.pdf"
count = 10
by = "Internet Archive"
url = "https://archive.org/details/plaidoyesecon00mari"
ppi = 300
note = "Scanned on scribe2.indiana.archive.org at the indiana centre."

[[resp]]
name = "Marion, Simon,baron de Druy"
role = "author"

[[resp]]
name = "Marion, Simon, baron de Druy"
role = "author"

[[resp]]
name = "Muret, Marc-Antoine, 1526-1585"
role = "author"

[[resp]]
name = "Du Puys, Jacques, d. 1589?"
role = "author"

[[resp]]
name = "Beys, Gilles, 1541?-1595"
role = "author"

[[resp]]
name = "[Paris"
role = "publisher"

[[text]]
file = "plaidoyesecon00mari.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "plaidoyesecon00mari.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "plaidoyesecon00mari.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "plaidoyesecon00mari.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "plaidoyesecon00mari.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "plaidoyesecon00mari.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "plaidoyesecon00mari.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "plaidoyesecon00mari.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"
