#:schema ../../../../schemas/source.json
layer = "source"
id = "scriptorvmgallim00unse"
type = "book"
title = "Scriptorvm Galliæ maledicentiae et advlationes impiæ."
language = "la"
date = "1635"
note = "Bibl. nat. Cat. de l'histoire de France."
url = "https://archive.org/details/scriptorvmgallim00unse"
subject = ["Richelieu, Armand Jean du Plessis, duc de, 1585-1642"]
extent = "59 p.20 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case F 39 .326 1635sc"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t1tf58p62"
internet_archive = "scriptorvmgallim00unse"

[scan]
file = "scriptorvmgallim00unse.pdf"
count = 70
by = "Internet Archive"
url = "https://archive.org/details/scriptorvmgallim00unse"
ppi = 500
note = "Scanned on scribe4.indiana.archive.org with a Canon EOS 5D Mark II at the indiana centre."

[[resp]]
name = "[S.l.],  1635"
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_667660"

[[text]]
file = "scriptorvmgallim00unse.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p9.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p10.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p11.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p12.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p13.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p14.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p15.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p16.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p17.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p18.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p19.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p20.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p21.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p22.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p23.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p24.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p25.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p26.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p27.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p28.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p29.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p30.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p31.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p32.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p33.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p34.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p35.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p36.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p37.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p38.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p39.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p40.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p41.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p42.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p43.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p44.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p45.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p46.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p47.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p48.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p49.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p50.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p51.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p52.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p53.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p54.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p55.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p56.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p57.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p58.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p59.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p60.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p61.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p62.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p63.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p64.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p65.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p66.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p67.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"

[[text]]
file = "scriptorvmgallim00unse.p68.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "la"
