#:schema ../../../../schemas/source.json
layer = "source"
id = "case_frc_17334"
type = "pamphlet"
title = "Suite au codicile de Boniface-Honoré Desbrugnières, écuyer-conseiller du roi, officier-commensal de sa maison, son exempt ordinaire & extraordinaire pour causes de police"
place = "France?"
date = "1788"
url = "https://archive.org/details/case_frc_17334"
subject = [
    "Desbrugnières, Fiacre-Pancrace-Honoré",
    "Wills",
    "Humor",
]
extent = "14 p. ; 22 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive."

[holding]
repository = "The Newberry Library"
shelfmark = "Case FRC 17334"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t5dc32r9v"
internet_archive = "case_frc_17334"

[scan]
file = "case_frc_17334.pdf"
count = 17
by = "Internet Archive"
url = "https://archive.org/details/case_frc_17334"

[[resp]]
name = "Desbrugnières, Fiacre-Pancrace-Honoré"
role = "author"

[[resp]]
name = "s.n.]"
role = "publisher"

[[link]]
rel = "catalogue"
url = "https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=835747"

[[text]]
file = "case_frc_17334.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p9.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p10.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p11.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p12.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p13.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p14.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p15.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_17334.p16.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
