#:schema ../../../../schemas/source.json
layer = "source"
id = "refonte00unse"
type = "book"
title = "Refonte de l'économie de l'Armée française, ou, Extrait et développement d'un plan militaire /"
language = "fr"
place = "A Paris"
date = "1787"
note = """"Au moyen de cette refonte le roi auroit 300000 hommes sur pied, le traitement de chaque individu employé dans cette grande armée seroit augmenté depuis le maréchal de France jusqu'aux fusiliers, et Sa Majesté feroit encore tous les ans une économie de douze millions sur les dépenses actuelles de la guerre.". Not in Martin & Walter. Révolution française. "Tableau des forces de terre du roi de France, partagées en trois armées différentes, disposé d'après un nouveau systême de stratégie, de logistique et d'économie ..."--Table on folded leaf. Scanner's note: No copyright page found. No table-of-contents pages found. Title and cover pages combined."""
url = "https://archive.org/details/refonte00unse"
subject = ["France. Armée"]
extent = "64 p., [1] folded leaf ; 20 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case FRC 26258"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t6k12f818"
internet_archive = "refonte00unse"

[scan]
file = "refonte00unse.pdf"
count = 70
by = "Internet Archive"
url = "https://archive.org/details/refonte00unse"
ppi = 500
note = "Scanned on scribe4.indiana.archive.org with a Canon EOS 5D Mark II at the indiana centre."

[[resp]]
name = "Tallien, Jean-Lambert, 1767-2543"
role = "author"

[[resp]]
name = "Wimpffen, Alexandre-Stanislas, baron de"
role = "author"

[[resp]]
name = "Didot, Pierre-François, 1731-1795"
role = "publisher"

[[resp]]
name = "Jombert, Alexandre, 1749-"
role = "publisher"

[[resp]]
name = "Chez Didot fils aîné : Jombert jeune, libraire pour l'artillerie et le génie, rue Dauphine, près le Pont-Neuf, no. 116"
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_780016"

[[text]]
file = "refonte00unse.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p9.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p10.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p11.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p12.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p13.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p14.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p15.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p16.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p17.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p18.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p19.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p20.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p21.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p22.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p23.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p24.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p25.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p26.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p27.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p28.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p29.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p30.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p31.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p32.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p33.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p34.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p35.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p36.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p37.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p38.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p39.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p40.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p41.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p42.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p43.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p44.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p45.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p46.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p47.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p48.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p49.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p50.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p51.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p52.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p53.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p54.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p55.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p56.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p57.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p58.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p59.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p60.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p61.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p62.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p63.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p64.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p65.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p66.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p67.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "refonte00unse.p68.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"
