#:schema ../../../../schemas/source.json
layer = "source"
id = "lhommeindiff00unse"
type = "pamphlet"
title = "L'Homme indifferent : en vers burlesques."
language = "fr"
place = "A Paris"
date = "1649"
note = "Title page arabesque. In verse. Reference: Moreau, C. Mazarinades 1659. Scanner's note: No copyright found. No table of contents found. Damaged, stained pages and cover.  Title on cover.<br />."
url = "https://archive.org/details/lhommeindiff00unse"
subject = ["Mazarinades"]
extent = "8 p. ;21 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case F 39 .326 1649sas"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t8sb9jr0g"
internet_archive = "lhommeindiff00unse"

[scan]
file = "lhommeindiff00unse.pdf"
count = 10
by = "Internet Archive"
url = "https://archive.org/details/lhommeindiff00unse"
ppi = 300
note = "Scanned on scribe2.indiana.archive.org at the indiana centre."

[[resp]]
name = "Sassier, Guillaume, d. 1685"
role = "bookseller"

[[resp]]
name = "Chez G[uillaume S[assier ruë des Cordiers, proche Sorbone, M. DC. XXXXIX. 1649]"
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_656274"

[[text]]
file = "lhommeindiff00unse.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lhommeindiff00unse.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lhommeindiff00unse.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lhommeindiff00unse.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lhommeindiff00unse.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lhommeindiff00unse.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lhommeindiff00unse.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lhommeindiff00unse.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"
