#:schema ../../../../schemas/source.json
layer = "source"
id = "lemiroirdutempsp00fanc"
type = "pamphlet"
title = "Le miroir du temps passé a l'vsage du present. A tous bons peres religieux, et vrais catholiques non passionnez ..."
language = "fr"
date = "1626"
note = "Binder's title: Pieces - 1623-25. Bibl. nat. Cat. de l'histoire de France. Scanner's note: No copyright found. No table of contents found.  Damaged, stained pages and cover.  Title on cover. <br />Tight margins. Text lost in binding. <br />Top of pages are torn creating missing text. <br /><br />."
url = "https://archive.org/details/lemiroirdutempsp00fanc"
extent = "[8], 64 p.18 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case F 39 .326 1623con no.3"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t2z37954m"
internet_archive = "lemiroirdutempsp00fanc"

[scan]
file = "lemiroirdutempsp00fanc.pdf"
count = 74
by = "Internet Archive"
url = "https://archive.org/details/lemiroirdutempsp00fanc"
ppi = 300
note = "Scanned on scribe2.indiana.archive.org at the indiana centre."

[[resp]]
name = "Fancan, François Dorval-Langlois,sieur de,approximately 1576-1628"
role = "author"

[[resp]]
name = "Fancan, François Dorval-Langlois, sieur de, approximately 1576-1628"
role = "author"

[[resp]]
name = "[n.p.,  1626?]"
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_360683"

[[text]]
file = "lemiroirdutempsp00fanc.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p9.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p10.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p11.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p12.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p13.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p14.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p15.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p16.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p17.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p18.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p19.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p20.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p21.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p22.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p23.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p24.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p25.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p26.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p27.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p28.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p29.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p30.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p31.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p32.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p33.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p34.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p35.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p36.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p37.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p38.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p39.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p40.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p41.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p42.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p43.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p44.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p45.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p46.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p47.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p48.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p49.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p50.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p51.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p52.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p53.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p54.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p55.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p56.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p57.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p58.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p59.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p60.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p61.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p62.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p63.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p64.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p65.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p66.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p67.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p68.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p69.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p70.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p71.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "lemiroirdutempsp00fanc.p72.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"
