#:schema ../../../../../schemas/source.json
id    = "journal-de-paris-1789-06-16-supplement"
layer = "document"
of    = "journal-de-paris-1789-vol1"
type  = "supplement"
supplement_to = "journal-de-paris-1789-06-16"
date  = "1789-06-16"
pages = { from = 805, to = 808 }
