#:schema ../../../../schemas/source.json
layer = "source"
id = "theoriedelambiti00hera"
type = "book"
title = "Théorie de l'ambition /"
language = "fr"
place = "Paris"
date = "1802"
note = """Notes by Jacques-Barthélemy Salgues. "De l'imprimerie de Ch. Pougens"--Colophon. Martin & Walter. Révolution française. BN. Bibliography: Martin & Walter.  Révolution française,  II, 16607. Scanner's note: No copyright page found. Title on cover. Damaged pages and cover. Last page of contents on back cover."""
url = "https://archive.org/details/theoriedelambiti00hera"
subject = [
    "Political science",
    "Maxims",
    "Education of princes",
]
extent = "102 p. ; 20 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case FRC 19708"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t01z96z9j"
internet_archive = "theoriedelambiti00hera"
openlibrary_edition = "OL26203715M"
openlibrary_work = "OL17600153W"

[scan]
file = "theoriedelambiti00hera.pdf"
count = 108
by = "Internet Archive"
url = "https://archive.org/details/theoriedelambiti00hera"
ppi = 500
note = "Scanned on scribe4.indiana.archive.org with a Canon EOS 5D Mark II at the indiana centre."

[[resp]]
name = "Hérault de Séchelles, Marie-Jean, 1759-1794"
role = "author"

[[resp]]
name = "Salgues, J. B. (Jacques Barthélemy), 1760-1830"
role = "author"

[[resp]]
name = "Pougens, Charles de, 1755-1833"
role = "printer"

[[resp]]
name = "Chez Bouquet, libraire, rue de Thionville, au Bon Sterne"
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_841216"

[[text]]
file = "theoriedelambiti00hera.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p9.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p10.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p11.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p12.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p13.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p14.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p15.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p16.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p17.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p18.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p19.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p20.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p21.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p22.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p23.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p24.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p25.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p26.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p27.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p28.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p29.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p30.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p31.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p32.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p33.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p34.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p35.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p36.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p37.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p38.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p39.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p40.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p41.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p42.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p43.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p44.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p45.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p46.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p47.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p48.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p49.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p50.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p51.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p52.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p53.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p54.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p55.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p56.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p57.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p58.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p59.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p60.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p61.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p62.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p63.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p64.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p65.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p66.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p67.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p68.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p69.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p70.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p71.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p72.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p73.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p74.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p75.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p76.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p77.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p78.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p79.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p80.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p81.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p82.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p83.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p84.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p85.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p86.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p87.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p88.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p89.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p90.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p91.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p92.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p93.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p94.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p95.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p96.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p97.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p98.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p99.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p100.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p101.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p102.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p103.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p104.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p105.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "theoriedelambiti00hera.p106.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"
