#:schema ../../../../schemas/source.json
layer = "source"
id = "adresse00fran_37"
type = "pamphlet"
title = "Adresse /"
language = "fr"
place = "À Paris"
date = "1798"
note = "Caption title. Imprint from colophon. Martin & Walter IV 2: 5681 [edition 1: 7 p.]. Scanner's note: No copyright page found. No table-of-contents pages found.  Title on cover. Damaged, stained pages and cover."
url = "https://archive.org/details/adresse00fran_37"
subject = ["Elections"]
extent = "7 p. ; 22 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case FRC 3212"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t9t202s2h"
internet_archive = "adresse00fran_37"

[scan]
file = "adresse00fran_37.pdf"
count = 10
by = "Internet Archive"
url = "https://archive.org/details/adresse00fran_37"
ppi = 500
note = "Scanned on scribe3.indiana.archive.org with a Canon EOS 5D Mark II at the indiana centre."

[[resp]]
name = "France. Directoire exécutif"
role = "author"

[[resp]]
name = "France. Directoire exécutif"
role = "author"

[[resp]]
name = "De l'Imprimerie de la République"
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_48071"

[[text]]
file = "adresse00fran_37.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "adresse00fran_37.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "adresse00fran_37.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "adresse00fran_37.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "adresse00fran_37.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "adresse00fran_37.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "adresse00fran_37.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "adresse00fran_37.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"
