#:schema ../../../../schemas/source.json
layer = "source"
id = "projetdelegislat00phil"
type = "book"
title = "Projet de législation civile, dans lequel on se propose de substituer un code général & simple, aux coutumes nombreuses & contradictoires qui régissent les diverses contrées de la France : dédié a l'Assemblée nationale /"
language = "fr"
place = "Mans?"
date = "1789"
note = "Not in Martin & Walter. Révolution française. Scanner's note: Title page and cover are combined. Damaged, stained, marked and/or loose pages. Uneven binding. Skewed text. <br />No Copyright found. No Table of Contents found. <br />."
url = "https://archive.org/details/projetdelegislat00phil"
subject = [
    "Civil law",
    "Customary law",
]
extent = "78 p. ; 20 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case FRC 23660"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t2f81nc47"
internet_archive = "projetdelegislat00phil"

[scan]
file = "projetdelegislat00phil.pdf"
count = 80
by = "Internet Archive"
url = "https://archive.org/details/projetdelegislat00phil"
ppi = 300
note = "Scanned on scribe2.indiana.archive.org at the indiana centre."

[[resp]]
name = "Philippeaux, Pierre, 1754-1794"
role = "author"

[[resp]]
name = "France. Assemblée nationale constituante (1789-1791)"
role = "author"

[[resp]]
name = "Chez Pivron, imprimeur-libraire, rue Marchande : Monnoyer, imprimeur-libraire, rue du Grande Pont-Neuf"
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_848101"

[[text]]
file = "projetdelegislat00phil.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p9.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p10.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p11.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p12.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p13.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p14.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p15.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p16.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p17.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p18.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p19.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p20.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p21.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p22.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p23.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p24.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p25.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p26.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p27.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p28.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p29.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p30.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p31.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p32.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p33.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p34.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p35.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p36.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p37.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p38.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p39.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p40.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p41.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p42.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p43.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p44.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p45.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p46.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p47.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p48.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p49.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p50.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p51.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p52.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p53.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p54.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p55.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p56.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p57.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p58.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p59.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p60.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p61.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p62.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p63.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p64.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p65.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p66.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p67.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p68.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p69.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p70.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p71.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p72.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p73.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p74.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p75.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p76.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p77.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "projetdelegislat00phil.p78.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"
