#:schema ../../../../schemas/source.json
layer = "source"
id = "opiniondecharles00pera_0"
type = "pamphlet"
title = "Opinion de Charles Perard, député de Maine et Loire, sur le jugement de Louis XVI"
language = "fr"
place = "France?"
date = "1793"
note = "Caption title. Publication date from Martin & Walter. Martin & Walter. Révolution française. Bibliography: Martin & Walter.  Révolution française, III, 26776. Scanner's note: No copyright page found. No table-of-contents pages found.  Title and cover are combined. Uneven binding. Skewed text. Damaged, stained and/or loose pages."
url = "https://archive.org/details/opiniondecharles00pera_0"
subject = [
    "Louis XVI, King of France, 1754-1793",
    "Representative government and representation",
]
extent = "8 p. ; 22 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case Wing DC137.08 .F73 v.14, no. 11"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t3810fj6w"
internet_archive = "opiniondecharles00pera_0"

[scan]
file = "opiniondecharles00pera_0.pdf"
count = 10
by = "Internet Archive"
url = "https://archive.org/details/opiniondecharles00pera_0"
ppi = 500
note = "Scanned on scribe10.indiana.archive.org with a Canon EOS 5D Mark II at the indiana centre."

[[resp]]
name = "Pérard, Charles François Jean, 176-1833"
role = "author"

[[resp]]
name = "Pérard, Charles François Jean, 1760-1833"
role = "author"

[[resp]]
name = "Louis XVI Trial and Execution Collection (Newberry Library) ICN"
role = "author"

[[resp]]
name = "s.n."
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_845683"

[[text]]
file = "opiniondecharles00pera_0.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "opiniondecharles00pera_0.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "opiniondecharles00pera_0.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "opiniondecharles00pera_0.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "opiniondecharles00pera_0.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "opiniondecharles00pera_0.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "opiniondecharles00pera_0.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"

[[text]]
file = "opiniondecharles00pera_0.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
lang = "fr"
