#:schema ../../../../schemas/source.json
layer = "source"
id = "deloffice00unse"
type = "pamphlet"
title = "De l'office & presceance de l'ecclesiastique & du magistrat."
date = "1591"
note = "Dedication signed: G.B., François royal. Lelong, Bibliothèque historique de la France. Scanner's note: No copyright found. No table of contents found.  Damaged, stained pages. <br />Some light text.<br /><br />."
url = "https://archive.org/details/deloffice00unse"
extent = "[8], 94 p.17 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case F 39 .326 1591cx"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t7cs17v4g"
internet_archive = "deloffice00unse"

[scan]
file = "deloffice00unse.pdf"
count = 118
by = "Internet Archive"
url = "https://archive.org/details/deloffice00unse"
ppi = 300
note = "Scanned on scribe2.indiana.archive.org at the indiana centre."

[[resp]]
name = "G. B"
role = "author"

[[resp]]
name = "[n.p.],  1591"
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_328072"

[[text]]
file = "deloffice00unse.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p9.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p10.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p11.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p12.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p13.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p14.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p15.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p16.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p17.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p18.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p19.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p20.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p21.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p22.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p23.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p24.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p25.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p26.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p27.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p28.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p29.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p30.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p31.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p32.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p33.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p34.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p35.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p36.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p37.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p38.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p39.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p40.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p41.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p42.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p43.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p44.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p45.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p46.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p47.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p48.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p49.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p50.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p51.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p52.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p53.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p54.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p55.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p56.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p57.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p58.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p59.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p60.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p61.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p62.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p63.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p64.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p65.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p66.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p67.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p68.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p69.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p70.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p71.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p72.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p73.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p74.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p75.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p76.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p77.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p78.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p79.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p80.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p81.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p82.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p83.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p84.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p85.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p86.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p87.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p88.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p89.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p90.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p91.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p92.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p93.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p94.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p95.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p96.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p97.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p98.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p99.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p100.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p101.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p102.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p103.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p104.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p105.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p106.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p107.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p108.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p109.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p110.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p111.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p112.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p113.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p114.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p115.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "deloffice00unse.p116.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
