#:schema ../../../../../schemas/source.json
id    = "journal-de-paris-1789-04-13"
layer = "document"
of    = "journal-de-paris-1789-vol1"
type  = "issue"
no    = 103
date  = "1789-04-13"
pages = { from = 469, to = 472 }
