#:schema ../../../../schemas/source.json
layer = "source"
id = "lepressoirdesesp00bour"
type = "book"
title = "Le pressoir des esponces du roy. Ou, Epistre l'iminaire de l'histoire de la Chambre de iustice, establie en l'an 1607. Pour la recherche des abus, maluersations & peculats commis és finances de Sa Maiesté ..."
date = "1624"
note = "Bibl. nat. Cat. gen. Scanner's note: Title page located on front cover. No copyright page found. No table-of-contents pages found. Worn, damaged and discolored pages and cover. Skewed text. Uneven binding."
url = "https://archive.org/details/lepressoirdesesp00bour"
extent = "54 p.16 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive, sponsored by The Newberry Library."

[holding]
repository = "The Newberry Library"
shelfmark = "Case F 39 .326 1624bou"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t3325dq4f"
internet_archive = "lepressoirdesesp00bour"

[scan]
file = "lepressoirdesesp00bour.pdf"
count = 62
by = "Internet Archive"
url = "https://archive.org/details/lepressoirdesesp00bour"
ppi = 500
note = "Scanned on scribe4.indiana.archive.org with a Canon EOS 5D Mark II at the indiana centre."

[[resp]]
name = "Bourgoin, J.(Jean)"
role = "author"

[[resp]]
name = "Bourgoin, J. (Jean)"
role = "author"

[[resp]]
name = "[n.p.],  1624"
role = "publisher"

[[link]]
rel = "catalogue"
url = "http://vufind.carli.illinois.edu/vf-nby/Record/nby_253574"

[[text]]
file = "lepressoirdesesp00bour.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p9.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p10.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p11.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p12.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p13.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p14.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p15.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p16.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p17.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p18.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p19.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p20.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p21.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p22.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p23.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p24.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p25.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p26.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p27.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p28.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p29.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p30.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p31.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p32.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p33.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p34.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p35.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p36.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p37.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p38.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p39.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p40.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p41.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p42.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p43.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p44.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p45.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p46.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p47.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p48.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p49.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p50.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p51.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p52.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p53.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p54.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p55.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p56.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p57.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p58.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p59.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "lepressoirdesesp00bour.p60.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
