#:schema ../../../../schemas/source.json
layer = "source"
id = "case_frc_16781"
type = "book"
title = "Mémoire sur le dessechement des marais, et l'utilité qu'on peut tirer des marais desséchés, en général & particulièrement de ceux du Laonois : qui, en 1787, a remporté le prix de la Société d'agriculture de Laon"
place = "A Paris"
date = "1789"
url = "https://archive.org/details/case_frc_16781"
subject = [
    "Reclamation of land",
    "Swamps",
]
extent = "iv, 103 p., II leaves of plates : maps ; 20 cm."

[rights]
work = "PD-old-100-expired"
scan = "PD"
attribution = "Digitised by the Internet Archive."

[holding]
repository = "The Newberry Library"
shelfmark = "Case FRC 16781"
collection = "French Revolution Collection"

[identifier]
ark = "ark:/13960/t36162q5r"
internet_archive = "case_frc_16781"

[scan]
file = "case_frc_16781.pdf"
count = 117
by = "Internet Archive"
url = "https://archive.org/details/case_frc_16781"

[[resp]]
name = "Cretté de Palluel, François, 1741-1798"
role = "author"

[[resp]]
name = "[s.n.]"
role = "publisher"

[[link]]
rel = "catalogue"
url = "https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=834610"

[[text]]
file = "case_frc_16781.p1.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p2.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p3.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p4.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p5.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p6.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p7.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p8.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p9.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p10.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p11.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p12.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p13.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p14.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p15.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p16.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p17.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p18.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p19.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p20.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p21.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p22.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p23.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p24.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p25.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p26.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p27.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p28.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p29.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p30.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p31.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p32.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p33.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p34.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p35.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p36.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p37.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p38.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p39.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p40.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p41.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p42.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p43.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p44.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p45.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p46.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p47.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p48.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p49.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p50.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p51.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p52.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p53.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p54.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p55.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p56.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p57.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p58.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p59.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p60.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p61.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p62.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p63.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p64.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p65.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p66.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p67.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p68.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p69.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p70.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p71.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p72.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p73.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p74.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p75.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p76.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p77.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p78.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p79.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p80.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p81.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p82.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p83.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p84.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p85.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p86.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p87.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p88.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p89.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p90.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p91.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p92.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p93.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p94.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p95.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p96.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p97.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p98.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p99.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p100.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p101.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p102.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p103.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p104.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p105.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p106.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p107.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p108.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p109.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p110.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p111.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p112.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p113.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p114.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p115.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"

[[text]]
file = "case_frc_16781.p116.ocr.md"
kind = "ocr"
by = "ABBYY FineReader 11.0"
